### ISSUE TITLE
Plugin won’t update while WP API Privacy is active

### ISSUE THREAD

**Issue by demetris** [wp-privacy/wp-api-privacy#1]
A reddit  user mentioned that the AIOS plugin won’t update when WP API Privacy is active.

Here is the subbredit thread:

https://www.reddit.com/r/Wordpress/comments/1glzjpy/today_i_learned_that_wordpress_sends_your_site/lvykukh/

**Comment by duanestorey** [comment]
Thanks.  This issue is fixed in main, and will be included in 1.0.2 when it goes out, likely tomorrow.

![Screenshot 2024-11-07 at 8 09 14 PM](https://github.com/user-attachments/assets/b4961d1f-3251-4a6f-8c9d-0493784b5adc)
