### ISSUE TITLE
Maybe add plugin action link for settings screen

### ISSUE THREAD

**Issue by demetris** [wp-privacy/wp-api-privacy#11]
Has this been omitted on purpose or is it on the todo list?

I can open a PR if the latter.

To be clear, by action link I mean a link added through this:

https://developer.wordpress.org/reference/hooks/plugin_action_links_plugin_file/

**Comment by duanestorey** [comment]
You mean having a link to the settings there?  Yes, it's on the to-do list!

**Comment by duanestorey** [comment]
This was included in 1.1.5.  Thanks for the reminder!
