### ISSUE TITLE
Fatal Error from the GitHub Updater script

### ISSUE THREAD

**Issue by ericsizemore** [wp-privacy/wp-api-privacy#14]
Hello,

I've run into an issue with the plugin, specifically the GitHub Updater; it placed my site into maintenance. After doing some digging, I came across a PHP Fatal Error in regard to this line:

https://github.com/wp-privacy/wp-api-privacy/blob/935a96779315b930111903c16fcc0317c0226397/src/github-updater.php#L177C21-L177C118

```
PHP Fatal error:  Uncaught Error: Attempt to assign property "tag_name" on string
```

```php
if ( $release->tag_name = $latestVersion && $release->target_commitish == $this->githubBranch ) {
```

Changing it to the following seems to have fixed the issue:

```php
if ( $release->tag_name == $latestVersion && $release->target_commitish == $this->githubBranch ) {
```

**Comment by duanestorey** [comment]
Ok thanks. That's strange because that's just something I was working on in main, it's not part of a release.  I'm not sure why Git Updater would grab it.

**Comment by ericsizemore** [comment]
No worries. And, I was playing around with the plugin so I just installed current dev. Though I believe the issue with

```php
$release->tag_name = $latestVersion
```

exists in all previous releases.

**Comment by duanestorey** [comment]
Yah, looks like a bug there, thanks.  It probably didn't fail before because it didn't have to do the boolean after it.   

So you basically told Git Updater to grab dev?  Is that an option in the plugin?  I just want to understand how it works as I've never used it.  Cheers.

**Comment by ericsizemore** [comment]
Sorry, it's late and my brain isn't working that great atm lol. I feel like I left out some key details.

I grabbed the dev here from GitHub to install the plugin initially, I didn't tell Git Updater to grab dev (I don't think that's an option?). It worked fine until I assume github-updater was triggered.

**Comment by duanestorey** [comment]
Oh ok.  No worries.  I was just worried I somehow released the dev version into the wild, but sounds like it was a one off.. Phew haha.  Thanks for finding that issue though.  I'll push out a release tomorrow with a few more changes.  If you have any suggestions, please let me know!

**Comment by ericsizemore** [comment]
No worries! My apologies for the panic! Haha.

**Comment by duanestorey** [comment]
All good!

**Comment by duanestorey** [comment]
This should be fixed now. Cheers

**Comment by markwaters** [comment]
I just downloaded and updated to 1.1.7 , now seeing this error in the admin interface.
"Plugin could not be activated because it triggered a fatal error."

**Comment by duanestorey** [comment]
Hey Mark.  Any idea where it's crashing, i.e. in your error log?  I have it running on two sites and they haven't hit any yet.

**Comment by markwaters** [comment]
Here you go -

`2024/11/11 17:56:36 [error] 863480#863480: *13246 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare WP_Privacy\WP_API_Privacy\initialize_privacy() (previously declared in /var/www/domain.tld/wp-content/plugins/wp-api-privacy/wp-api-privacy.php:32) in /var/www/domain.tld/wp-content/plugins/wp-api-privacy-1/wp-api-privacy.php on line 37" while reading response header from upstream, client: XXX.XXX.XXX.XXX, server: domain.tld, request: "GET /wp-admin/plugins.php?action=activate&plugin=wp-api-privacy-1%2Fwp-api-privacy.php&_wpnonce=0742664227 HTTP/2.0", upstream: "fastcgi://unix:/run/php/php8.3-fpm.sock:", host: "domain.tld", referrer: "https://domain.tld/wp-admin/update.php?action=upload-plugin"`

I also tried deleting the plugin and installing this latest version from the zip file again.

**Comment by duanestorey** [comment]
Any chance you have another version in another directory?  One of the older ZIP files might have installed in something like wp-privacy-1.1 or something.

**Comment by duanestorey** [comment]
Can you attach the ZIP you used as well, or point me at the download location (Github has a few different ZIPs)

**Comment by markwaters** [comment]
Awesome.
I had two directories  - wp-api-privacy and wp-api-privacy-1 
Nuked them both and installed the latest zip file.
All working as expected.
Thank you for the plugin and support , apologies for not checking more myself.

**Comment by duanestorey** [comment]
Ok awesome, no worries, thanks for letting me know.
