### ISSUE TITLE
Discussion - count of modifications

### ISSUE THREAD

**Issue by ThomasFireheart** [wp-privacy/wp-api-privacy#2]
Thoughts on creating a simple 'setting' that could toggle on or off the counting of times the "modifyCurl" has run ? It might be interesting for people to see a count of how much data is sent to WP. Figuring out where to store those counts (transients, in memory/redis cache) could impact page render speed, but it might be interesting to be able to see this plugin 'in action'.

**Comment by duanestorey** [comment]
Yah I did consider this.  I was trying to avoid having a setting's page, but maybe I should add one, along with a simple count like that. Thanks for the suggestion.

**Comment by drzimp402** [comment]
If there is a settings page, I’d like to suggest 2 additions.

1) Users being able to define what string to use in the user agent
replacement

2) A toggle to enable logging of requests. Just to show how often external
calls are made.

**Comment by duanestorey** [comment]
> 2) A toggle to enable logging of requests. Just to show how often external
calls are made.

I've been using the 'HTTP Requests Manager' - it keeps track of all the outbound requests, so you may want to check that out.

**Comment by duanestorey** [comment]
Version 1.1.3 contains basic statistics for how many API requests have been modified.
