### ISSUE TITLE
Default behaviour

### ISSUE THREAD

**Issue by pimschaaf** [wp-privacy/wp-api-privacy#20]
Hey @duanestorey, just had a quick read through the code. 

Looking at [function modifyUserAgent()](https://github.com/wp-privacy/wp-api-privacy/blob/main/src/api-privacy.php#L107) am I right to understand that by default (with privacy options turned off) it _mimics_ WordPress' default behaviour?

If so, I'm wondering about your reasoning behind this. 
Would not it be easier (maybe even expected) to leave $params unchanged by default, instead of maintaining the mimicking?

**Comment by duanestorey** [comment]
It ends up being exactly the same.  As far as I'm aware, the User Agent has been like that for over 15 years.

Why is this a concern?

**Comment by pimschaaf** [comment]
Would it make sense to leave the user-agent untouched unless modifications are desired? 
This could possibly simplify the code and ensure it stays aligned with WordPress automatically.

Simply because there _is_ the possibility to turn all options - or some of them - off; in which case I'd expect default (not mimicked) behaviour.

Thanks for your work — just wanted to share this thought!

**Comment by duanestorey** [comment]
Thanks, I'll take it into consideration.
