### ISSUE TITLE
Delete Setting Option on Uninstall

### ISSUE THREAD

**Issue by PluginVulnerabilities** [wp-privacy/wp-api-privacy#22]
We did a security review of the plugin and found a minor issue, though not with a security implication for this plugin. The plugin doesn't currently delete the option storing the plugin's setting when the plugin is uninstalled as plugins are supposed to do. That can be [handled](https://developer.wordpress.org/plugins/plugin-basics/uninstall-methods/) with either a register_uninstall_hook or an uninstall.php file.

**Comment by duanestorey** [comment]
Thanks for checking the plugin out - I'll add the settings removal in the next release, cheers.

**Comment by duanestorey** [comment]
This should be working now in 1.2.2.  Thanks for submitting.
