### ISSUE TITLE
Some misspelled URI strings in the plugin's main file

### ISSUE THREAD

**Issue by jessuppi** [wp-privacy/wp-api-privacy#5]
This is a really cool project @duanestorey and thanks for sharing it with the community! Just a quick note that it appears there are some misspelled URI strings:

https://github.com/wp-privacy/wp-api-privacy/blob/main/wp-api-privacy.php

These lines are missing a `-` (dash) it seems:

```
Plugin URI: https://github.com/wpprivacy/wp-api-privacy
Update URI: https://github.com/wpprivacy/wp-api-privacy
```

Also if possible I might suggest adding the following 2 lines to the plugin header as well:

```
GitHub Plugin URI: wp-privacy/wp-api-privacy
Primary Branch: main
```

Even though you're not using Git Updater, these lines could allow other projects like Git Updater or my own RepoMan to more easily identify the plugin as being hosted on GitHub, and I don't think it would conflict with your own mechanism. Or if you have another idea about how GitHub-based plugins could identify themselves, I'm asking around...

**Comment by duanestorey** [comment]
Thanks for that. The original name of the account I set up was wpprivacy, which is why those links ended up that way - fixed, thanks for reporting.  I added those headers as well, they'll be in the next release tonight, version 1.1.0

**Comment by jessuppi** [comment]
FYI we have now added WP API Privacy to our supported plugins in RepoMan 1.7.2:

https://github.com/littlebizzy/repoman
