### ISSUE TITLE
Maybe use composer/installers to allow for custom install path when using composer

### ISSUE THREAD

**Issue by demetris** [wp-privacy/wp-api-privacy#6]
I tried to install wp-api-privacy in a WordPress setup that is managed by composer *in its whole* (a Bedrock installation) and has a single composer.json (at the root dir).

This is not possible at the moment, but it would be possible if wp-api-privacy required composer/installers (I believe that’s how it works).

https://getcomposer.org/doc/faqs/how-do-i-install-a-package-to-a-custom-path-for-my-framework.md

https://github.com/composer/installers

Cheers!

**Comment by duanestorey** [comment]
Hi, I'm not super familiar with composer, but I did add it as a package previously.

You can install it using the command:
```
composer create-project wp-privacy/wp-api-privacy
````

But after that it will rely on the Github update mechanism within the plugin.  

Does that work, or are you after something else?

**Comment by demetris** [comment]
Hey,

I was thinking more of a scenario where **everything** is *always** managed in composer.

I am not an expert on composer myself either :-D but I could help if you think the time to do something like this is now.

##  So how do you manage plugins via composer only?

It’s easy these days. All dotorg plugins (and themes) are available in the form of Composer packages thanks to wpackagist.org. Several plugins not on dotorg also offer Composer packages. For example, ACF PRO. (And now, after the takeover, the free version of ACF as well.)

So you can install most of your plugins, and often all your plugins, using `composer require <plugin-name>`. It itself this is not that different from doing `wp plugin install <plugin-name>` but it offers a great advantage if you control your application code via Git: You can gitignore the whole plugins directory and now, instead of hundreds or thousands files, Git only needs to track two files as far as plugins go: composer.json and composer.lock

(Another great advantage you get if you also manage core via Composer is that you can set `DISALLOW_FILE_MODS` to true, so that no one can install/uninstall/update plugins/core via the admin interface.)

Then you manage your plugins using branches and Composer. Say you want to install wp-api-privacy:

-   You make a new branch: — plugins/install-wp-api-privacy
-   You switch to it and run `composer require wp-privacy/wp-api-privacy`
-   You commit the changes (just two files since the plugins dir is gitignored) and push the branch to your remote
-   You merge the branch into your staging branch.

Now your staging branch is set to automatically do a deployment when it gets a merge. `composer install` is run as part of that and, when the app is finally deployed to the staging site, you have the exact set of plugins/versions that’s specified in composer.lock

It all can be more complex or more simple than this, depending on what you need. But managing plugins via composer (and Git) is great when you get used to it.

There are also tools that help you set up WordPress like this. The best-known, and maybe the best, is Bedrock: https://roots.io/bedrock/

For setting a plugin to support all that, you can have a look at the ACF source code.

The ACF docs also have instructions for installing the plugins via Composer:

https://www.advancedcustomfields.com/resources/installing-acf-with-composer/

https://www.advancedcustomfields.com/resources/installing-acf-pro-with-composer/

I hope all this all was helpful and hasn’t just confused you about why people would want to use Composer to manage plugins. :-)

Demetris

**Comment by duanestorey** [comment]
So basically you want the entire website in composer?  So like in the root of your website, you'd run 
```
composer require wp-privacy/wp-api-privacy
```
and it would install it into wp-content/plugins?  Is that right?  I can play around to see if I can make that work.

**Comment by demetris** [comment]
Yep!

If it helps, I am attaching the composer.json for one of the local installations I use for testing and playing around. This particular installation was set up with Bedrock, so you’ll notice that the plugin, theme, and core installation paths specified are not the conventional ones.

But that is not something that you, as the author of the wp-api-privacy package, need to worry about. This is what the user of your package wants to do.

[composer.json](https://github.com/user-attachments/files/17686203/composer.json)

**Comment by duanestorey** [comment]
Ok I think I got it working.  Try doing a:
```
composer require wp-privacy/wp-api-privacy
```
I tagged 1.1.1 that seems to install into the wp-content/plugins directory now.

**Comment by demetris** [comment]
:-)

You did indeed.

You are fast!

The version (on the plugins page, pulled from the Version: field of the header in the PHP file) still says 1.1.0. But I think you know that.

Thank you!

**Comment by duanestorey** [comment]
Yah it's not a real release, I just tagged it for composer to test it out.  Go ahead and uninstall it and I'll do a proper release here to include all of that. I'll drop a comment here when it's done.

**Comment by duanestorey** [comment]
Ok, 1.1.2 is live, you should be good to go.  Thanks for your help making this work.  I'm sort of new to Git plugins and composer, but seems pretty slick.
