### ISSUE TITLE
Investigate issue with Git Updater

### ISSUE THREAD

**Issue by duanestorey** [wp-privacy/wp-api-privacy#7]
There might be a potential conflict between the update mechanism of the plugin, and Git Updater.

**Comment by afragen** [comment]
I should be able to test this and will report back. 

Do you have any specific workflows I should test that concern you?

**Comment by duanestorey** [comment]
Well, I'm using the release API on Github to generate the change-log and grab the download URL.  I guess I'm worried Git Updater will intercept that and do it's own thing, like break the change log code etc.  I'm not sure how it works.  I think I'd probably prefer for Git Updater to be able to install the plugin (which I'm guessing it can do via the tags), but somehow be told (maybe via the same tags), to not worry about the updates itself if that makes sense.  I'm happy to investigate a bit too, I just don't want to two stomping on each other if that makes sense, since they will likely both be trying to do an update.

**Comment by afragen** [comment]
Where does your plugin pull the changelog from?

**Comment by duanestorey** [comment]
@afragen it doesn't - it generates it dynamically from the Github releases.

**Comment by afragen** [comment]
It seems as if Git Updater simply takes over.

**Comment by duanestorey** [comment]
Any way to maybe tell it not to, like some other info in the Plugin Header?  I don't want to make it complicated, but would be nice if everything plays well together.

**Comment by afragen** [comment]
I don't think so. I have an Ignore class and I tried that. It didn't work. 

The only thing that isn't the same is the View details modal. It could be same or close enough if you created a CHANGES.md file. 

Otherwise the only benefits would be for things you don't do with your updater like branch switching.

**Comment by duanestorey** [comment]
I have a banner image specified for that modal - do you have some way to handle that as well?

**Comment by afragen** [comment]
If it's in the assets directory it should pull in. If not there's a filter to specify the location.

**Comment by duanestorey** [comment]
Do you have any docs talking about where the image(s) go, and the CHANGES.md etc?  I'll see if I can make it all compliant.  Thanks.

**Comment by afragen** [comment]
https://git-updater.com/knowledge-base/usage/


Filter documented here. 
https://github.com/afragen/git-updater/blob/c67c9e868076b1cf2f933e5223c57ed38867e5b9/src/Git_Updater/Plugin.php#L210

**Comment by duanestorey** [comment]
Perfect, thanks.  I didn't see anything about CHANGES.md, except what I found here:
https://github.com/afragen/git-updater/blob/develop/CHANGES.md

Just make it look like that?  I think I read I can use CHANGELOG.md as well?

**Comment by wp-privacy** [comment]
Ok this is in there now, hopefully it all works.  Cheers.

**Comment by duanestorey** [comment]
Hey @afragen  - a user just commented here - https://github.com/wp-privacy/wp-api-privacy/issues/14 that their plugin updated with Git Updater, but that it crashed.  It had picked up a change I made in main that's not part of a tag or release.  How does Git Updater know what to pull, is it not from the Release zip files?

**Comment by afragen** [comment]
Looks like it works great!
