### ISSUE TITLE
PHP Fatal Error when "network activated"

### ISSUE THREAD

**Issue by PraetorIM** [wp-privacy/wp-api-privacy#9]
2024-11-09 10:26:53.317011 [NOTICE] [3470] [T0] [89.0.208.206:59913-H3:A6D493F0EF36D8B3-88#APVH_praetor.eu:443] [STDERR] PHP Fatal error:  Uncaught Error: Call to undefined function wp_get_current_user() in /var/www/[...]/wp-includes/capabilities.php:911
Stack trace:
#0 /var/www/[...]/wp-admin/network/settings.php(16): current_user_can()
#1 /var/www/[...]/wp-content/plugins/wp-api-privacy/src/api-privacy.php(11): require_once('...')
#2 /var/www/[...]/wp-content/plugins/wp-api-privacy/wp-api-privacy.php(30): require_once('...')
#3 /var/www/[...]/wp-settings.php(471): include_once('...')
#4 /var/www/[...]/wp-config.php(148): require_once('...')
#5 /var/www/[...]/wp-load.php(55): require_once('...')
#6 /var/www/[...]/wp-admin/admin.php(34): require_once('...')
#7 /var/www/[...]/wp-admin/network/admin.php(13): require_once('...')
#8 /var/www/[...]/wp-admin/network/index.php(11): require_once('...')
#9 {main}
thrown in /var/www/[...]/wp-includes/capabilities.php on line 911

The error only appears in Network Admin.

**Comment by iolaire** [comment]
I experienced the same issue.  Activates fine on individual multisite site dashboards.  Thanks for the plugin.

**Comment by duanestorey** [comment]
Thanks, I'm working on this now.  

What is the use case you would like?  Basically to network activate the plugin, but still configure the options for it at the individual site level?

**Comment by duanestorey** [comment]
Try version 1.1.3 and see if that fixes your issue.  Right now nothing special is being done in multisite - basically each subsite can still configure their options individually.

**Comment by iolaire** [comment]
> Try version 1.1.3 and see if that fixes your issue. Right now nothing special is being done in multisite - basically each subsite can still configure their options individually.

Yes it successfully networked activated for me with all the default blocks set on a newly activated site.  I'm not multiuser user of multisite so take my suggestion with a grain of salt but I prefer your suggestion _"Basically to network activate the plugin, but still configure the options for it at the individual site level?"_

**Comment by PraetorIM** [comment]
Thank you. Version 1.1.3 fixed the issue.

> What is the use case you would like? Basically to network activate the plugin, but still configure the options for it at the individual site level?

At the moment network activation is fine. 
An option to configure the entire multisite is not so important, as in the multisite only the main website starts the requests to wp.org anyway.

**Comment by duanestorey** [comment]
Great, thanks for the update. If you need anything else, let me know
